
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'it' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  it: {
    // Index page translations
    heroTitle: "Virtuosity",
    heroSubtitle: "Un modello innovativo che stimola l'interazione tra comuni, aziende e cittadini per costruire insieme un futuro sostenibile.",
    heroDescription: "La piattaforma che premia i tuoi comportamenti sostenibili. Tracciamento automatico, certificati blockchain e premi reali per un futuro più verde.",
    buttonVirtusosity: "Virtusosity",
    buttonUser: "Utente",
    buttonExchange: "Exchange",
    buttonCompanies: "Aziende",
    buttonMunicipalities: "Comuni",
    switchToEnglish: "Switch to English",
    englishVersion: "English Version",
    englishComingSoon: "English translation coming soon! 🇬🇧",
    reportTitle: "Report Virtuosity",
    reportSubtitle: "Report Attività Sostenibili",
    reportDescription: "Riepilogo completo delle tue attività e certificazioni - Periodo: Gennaio 2024",
    downloadReport: "Scarica Report",
    backToDashboard: "Torna alla Dashboard",
    totalCO2Saved: "CO₂ Totale Risparmiata",
    totalPoints: "Punti Totali",
    certifiedCO2: "CO₂ Certificata",
    certifiedPoints: "Punti Certificati",
    activitiesDetail: "Dettaglio Attività",
    activitiesDescription: "Elenco completo di tutte le attività sostenibili registrate",
    blockchainCertificates: "Certificati Blockchain",
    certificatesDescription: "Certificazioni digitali verificate e immutabili",
    backToMenu: "Torna al Menu",
    employeeCertificates: "Certificati Dipendenti",
    externalCertificates: "Certificati Esterni",
    employeeCertificatesDesc: "Certificati DPP ricevuti dai dipendenti aziendali",
    externalCertificatesDesc: "Certificati DPP ricevuti da soggetti esterni",
    welfareTitle: "Welfare, Premi e Gadget Aziendali",
    welfareDescription: "Gestisci i premi welfare, gadget aziendali e viaggi premio disponibili per i dipendenti",
    type: "Tipo",
    name: "Nome",
    value: "Valore",
    add: "Aggiungi",
    sustainabilityReport: "Report Bilancio di Sostenibilità",
    sustainabilityDescription: "Genera report con i dati per il bilancio di sostenibilità aziendale",
    certifyAndCompensate: "Certifica e Compensa",
    close: "Chiudi",
    exportReport: "Esporta Report",
    activityType: "Tipo",
    activity: "Attività",
    distance: "Distanza",
    co2Saved: "CO₂ Risp.",
    points: "Punti",
    date: "Data",
    location: "Luogo",
    id: "ID",
    title: "Titolo",
    certifiedCO2Short: "CO₂ Certificata",
    validationDate: "Data Validazione",
    blockchainHash: "Hash Blockchain",
    status: "Stato",
    verified: "Verificato",
    aboutValueOfActions: "Il valore delle azioni quotidiane",
    aboutOurMission: "La Nostra Missione",
    aboutMissionText: "Democratizzare la sostenibilità attraverso la tecnologia blockchain, rendendo ogni azione sostenibile misurabile, verificabile e premiabile. Costruiamo un futuro dove fare la scelta giusta per il pianeta diventa anche la scelta più conveniente per le persone.",
    aboutHowItWorks: "Come Funziona Virtuosity",
    aboutStartNow: "Inizia Ora",
    aboutHome: "Home",
    aboutBackHome: "Torna alla Home",
    // New About page translations
    aboutDescription: "Virtuosity è la prima piattaforma europea che trasforma automaticamente i comportamenti sostenibili in certificati verificabili, creando un ecosistema di incentivi concreti per cittadini, aziende e pubbliche amministrazioni.",
    trackingAutomatico: "Tracking Automatico",
    trackingDesc: "Nessun input manuale. Le tue azioni sostenibili vengono rilevate automaticamente tramite sensori del telefono e integrazioni con app esterne.",
    certificazioneBlockchain: "Certificazione Blockchain",
    certificazioneDesc: "Ogni azione genera 4 tipologie di certificati digitali verificabili e immutabili su blockchain Ethereum/Polygon: CO2, Rifiuti e Riciclo, Risparmio Energetico e Acqua.",
    premiReali: "Premi Reali",
    premiDesc: "Converti i tuoi certificati in benefit aziendali, sconti sui trasporti, ingressi gratuiti e molto altro tramite il marketplace integrato.",
    communityGamification: "Community & Gamification",
    communityDesc: "Partecipa a sfide, conquista badge, scala le classifiche e connettiti con altri cittadini virtuosi nella community sostenibile.",
    certificatiCO2: "Certificati CO2",
    certificatiCO2Desc: "Riduzione emissioni attraverso mobilità sostenibile",
    rifiutiRiciclo: "Rifiuti e Riciclo",
    rifiutiRicicloDesc: "Gestione responsabile e riciclo dei materiali",
    risparmiEnergetico: "Risparmio Energetico",
    risparmiEnergeticoDesc: "Ottimizzazione consumi e efficienza energetica",
    certificatiAcqua: "Certificati Acqua",
    certificatiAcquaDesc: "Conservazione e uso responsabile delle risorse idriche",
    integrazioneDpp: "Integrazione con Digital Product Passports (DPP)",
    integrazioneDppDesc: "Virtuosity sarà tra le prime piattaforme europee ad integrare i Digital Product Passports, rivoluzionando la tracciabilità e sostenibilità dei prodotti secondo la normativa EU 2024",
    privacySecurity: "Privacy e Sicurezza con Zero-Knowledge Proofs",
    privacyDesc: "La tua privacy è al sicuro grazie alle Zero-Knowledge Proofs (ZKP), che permettono di verificare i tuoi comportamenti sostenibili senza rivelare dati personali sensibili",
    perCittadini: "Per i Cittadini",
    perCittadiniDesc: "Premi concreti per comportamenti sostenibili quotidiani",
    perAziende: "Per le Aziende",
    perAziendeDesc: "Strumenti ESG avanzati e coinvolgimento dei dipendenti",
    perCitta: "Per le Città",
    perCittaDesc: "Dati real-time per politiche di sostenibilità efficaci",
    ilNostroTeam: "Il Nostro Team",
    iNostriAdvisors: "I Nostri Advisors",
    offertaCommerciale: "Offerta Commerciale",
    pianoMicro: "Piano Micro",
    pianoPMI: "Piano PMI",
    pianoEnterprise: "Piano Enterprise",
    iniziaSubito: "Inizia Subito",
    contattaci: "Contattaci"
  },
  en: {
    // Index page translations
    heroTitle: "Virtuosity",
    heroSubtitle: "An innovative model that stimulates interaction between municipalities, companies and citizens to build a sustainable future together.",
    heroDescription: "The platform that rewards your sustainable behaviors. Automatic tracking, blockchain certificates and real rewards for a greener future.",
    buttonVirtusosity: "Virtusosity",
    buttonUser: "User",
    buttonExchange: "Exchange",
    buttonCompanies: "Companies",
    buttonMunicipalities: "Municipalities",
    switchToEnglish: "Passa all'Italiano",
    englishVersion: "Versione Italiana",
    englishComingSoon: "Traduzione italiana già disponibile! 🇮🇹",
    reportTitle: "Virtuosity Report",
    reportSubtitle: "Sustainable Activities Report",
    reportDescription: "Complete summary of your activities and certifications - Period: January 2024",
    downloadReport: "Download Report",
    backToDashboard: "Back to Dashboard",
    totalCO2Saved: "Total CO₂ Saved",
    totalPoints: "Total Points",
    certifiedCO2: "Certified CO₂",
    certifiedPoints: "Certified Points",
    activitiesDetail: "Activities Detail",
    activitiesDescription: "Complete list of all registered sustainable activities",
    blockchainCertificates: "Blockchain Certificates",
    certificatesDescription: "Verified and immutable digital certifications",
    backToMenu: "Back to Menu",
    employeeCertificates: "Employee Certificates",
    externalCertificates: "External Certificates",
    employeeCertificatesDesc: "DPP certificates received from company employees",
    externalCertificatesDesc: "DPP certificates received from external subjects",
    welfareTitle: "Corporate Welfare, Rewards and Gadgets",
    welfareDescription: "Manage welfare rewards, corporate gadgets and prize trips available for employees",
    type: "Type",
    name: "Name",
    value: "Value",
    add: "Add",
    sustainabilityReport: "Sustainability Report",
    sustainabilityDescription: "Generate reports with data for corporate sustainability reporting",
    certifyAndCompensate: "Certify and Compensate",
    close: "Close",
    exportReport: "Export Report",
    activityType: "Type",
    activity: "Activity",
    distance: "Distance",
    co2Saved: "CO₂ Saved",
    points: "Points",
    date: "Date",
    location: "Location",
    id: "ID",
    title: "Title",
    certifiedCO2Short: "Certified CO₂",
    validationDate: "Validation Date",
    blockchainHash: "Blockchain Hash",
    status: "Status",
    verified: "Verified",
    aboutValueOfActions: "The value of daily actions",
    aboutOurMission: "Our Mission",
    aboutMissionText: "Democratize sustainability through blockchain technology, making every sustainable action measurable, verifiable and rewarding. We build a future where making the right choice for the planet also becomes the most convenient choice for people.",
    aboutHowItWorks: "How Virtuosity Works",
    aboutStartNow: "Start Now",
    aboutHome: "Home",
    aboutBackHome: "Back to Home",
    // New About page translations
    aboutDescription: "Virtuosity is the first European platform that automatically transforms sustainable behaviors into verifiable certificates, creating an ecosystem of concrete incentives for citizens, companies and public administrations.",
    trackingAutomatico: "Automatic Tracking",
    trackingDesc: "No manual input. Your sustainable actions are automatically detected through phone sensors and integrations with external apps.",
    certificazioneBlockchain: "Blockchain Certification",
    certificazioneDesc: "Every action generates 4 types of verifiable and immutable digital certificates on Ethereum/Polygon blockchain: CO2, Waste and Recycling, Energy Saving and Water.",
    premiReali: "Real Rewards",
    premiDesc: "Convert your certificates into corporate benefits, transport discounts, free admissions and much more through the integrated marketplace.",
    communityGamification: "Community & Gamification",
    communityDesc: "Participate in challenges, earn badges, climb leaderboards and connect with other virtuous citizens in the sustainable community.",
    certificatiCO2: "CO2 Certificates",
    certificatiCO2Desc: "Emission reduction through sustainable mobility",
    rifiutiRiciclo: "Waste and Recycling",
    rifiutiRicicloDesc: "Responsible management and recycling of materials",
    risparmiEnergetico: "Energy Saving",
    risparmiEnergeticoDesc: "Consumption optimization and energy efficiency",
    certificatiAcqua: "Water Certificates",
    certificatiAcquaDesc: "Conservation and responsible use of water resources",
    integrazioneDpp: "Integration with Digital Product Passports (DPP)",
    integrazioneDppDesc: "Virtuosity will be among the first European platforms to integrate Digital Product Passports, revolutionizing product traceability and sustainability according to EU 2024 regulations",
    privacySecurity: "Privacy and Security with Zero-Knowledge Proofs",
    privacyDesc: "Your privacy is safe thanks to Zero-Knowledge Proofs (ZKP), which allow verifying your sustainable behaviors without revealing sensitive personal data",
    perCittadini: "For Citizens",
    perCittadiniDesc: "Concrete rewards for daily sustainable behaviors",
    perAziende: "For Companies",
    perAziendeDesc: "Advanced ESG tools and employee engagement",
    perCitta: "For Cities",
    perCittaDesc: "Real-time data for effective sustainability policies",
    ilNostroTeam: "Our Team",
    iNostriAdvisors: "Our Advisors",
    offertaCommerciale: "Commercial Offer",
    pianoMicro: "Micro Plan",
    pianoPMI: "SME Plan",
    pianoEnterprise: "Enterprise Plan",
    iniziaSubito: "Start Now",
    contattaci: "Contact Us"
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('it');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['it']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
