
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'it' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  it: {
    // Index page translations
    heroTitle: "Virtuosity",
    heroSubtitle: "Un modello innovativo che stimola l'interazione tra comuni, aziende e cittadini per costruire insieme un futuro sostenibile.",
    heroDescription: "La piattaforma che premia i tuoi comportamenti sostenibili. Tracciamento automatico, certificati blockchain e premi reali per un futuro più verde.",
    buttonVirtusosity: "Virtusosity",
    buttonUser: "Utente",
    buttonExchange: "Exchange",
    buttonCompanies: "Aziende",
    buttonMunicipalities: "Comuni",
    switchToEnglish: "Switch to English",
    englishVersion: "English Version",
    englishComingSoon: "English translation coming soon! 🇬🇧",
    reportTitle: "Report Virtuosity",
    reportSubtitle: "Report Attività Sostenibili",
    reportDescription: "Riepilogo completo delle tue attività e certificazioni - Periodo: Gennaio 2024",
    downloadReport: "Scarica Report",
    backToDashboard: "Torna alla Dashboard",
    totalCO2Saved: "CO₂ Totale Risparmiata",
    totalPoints: "Punti Totali",
    certifiedCO2: "CO₂ Certificata",
    certifiedPoints: "Punti Certificati",
    activitiesDetail: "Dettaglio Attività",
    activitiesDescription: "Elenco completo di tutte le attività sostenibili registrate",
    blockchainCertificates: "Certificati Blockchain",
    certificatesDescription: "Certificazioni digitali verificate e immutabili",
    backToMenu: "Torna al Menu",
    employeeCertificates: "Certificati Dipendenti",
    externalCertificates: "Certificati Esterni",
    employeeCertificatesDesc: "Certificati DPP ricevuti dai dipendenti aziendali",
    externalCertificatesDesc: "Certificati DPP ricevuti da soggetti esterni",
    welfareTitle: "Welfare, Premi e Gadget Aziendali",
    welfareDescription: "Gestisci i premi welfare, gadget aziendali e viaggi premio disponibili per i dipendenti",
    type: "Tipo",
    name: "Nome",
    value: "Valore",
    add: "Aggiungi",
    sustainabilityReport: "Report Bilancio di Sostenibilità",
    sustainabilityDescription: "Genera report con i dati per il bilancio di sostenibilità aziendale",
    certifyAndCompensate: "Certifica e Compensa",
    close: "Chiudi",
    exportReport: "Esporta Report",
    activityType: "Tipo",
    activity: "Attività",
    distance: "Distanza",
    co2Saved: "CO₂ Risp.",
    points: "Punti",
    date: "Data",
    location: "Luogo",
    id: "ID",
    title: "Titolo",
    certifiedCO2Short: "CO₂ Certificata",
    validationDate: "Data Validazione",
    blockchainHash: "Hash Blockchain",
    status: "Stato",
    verified: "Verificato",
    aboutValueOfActions: "Il valore delle azioni quotidiane",
    aboutOurMission: "La Nostra Missione",
    aboutMissionText: "Democratizzare la sostenibilità attraverso la tecnologia blockchain, rendendo ogni azione sostenibile misurabile, verificabile e premiabile. Costruiamo un futuro dove fare la scelta giusta per il pianeta diventa anche la scelta più conveniente per le persone.",
    aboutHowItWorks: "Come Funziona Virtuosity",
    aboutStartNow: "Inizia Ora",
    aboutHome: "Home",
    aboutBackHome: "Torna alla Home",
    // New About page translations
    aboutDescription: "Virtuosity è la prima piattaforma europea che trasforma automaticamente i comportamenti sostenibili in certificati verificabili, creando un ecosistema di incentivi concreti per cittadini, aziende e pubbliche amministrazioni.",
    trackingAutomatico: "Tracking Automatico",
    trackingDesc: "Nessun input manuale. Le tue azioni sostenibili vengono rilevate automaticamente tramite sensori del telefono e integrazioni con app esterne.",
    certificazioneBlockchain: "Certificazione Blockchain",
    certificazioneDesc: "Ogni azione genera 4 tipologie di certificati digitali verificabili e immutabili su blockchain Ethereum/Polygon: CO2, Rifiuti e Riciclo, Risparmio Energetico e Acqua.",
    premiReali: "Premi Reali",
    premiDesc: "Converti i tuoi certificati in benefit aziendali, sconti sui trasporti, ingressi gratuiti e molto altro tramite il marketplace integrato.",
    communityGamification: "Community & Gamification",
    communityDesc: "Partecipa a sfide, conquista badge, scala le classifiche e connettiti con altri cittadini virtuosi nella community sostenibile.",
    certificatiCO2: "Certificati CO2",
    certificatiCO2Desc: "Riduzione emissioni attraverso mobilità sostenibile",
    rifiutiRiciclo: "Rifiuti e Riciclo",
    rifiutiRicicloDesc: "Gestione responsabile e riciclo dei materiali",
    risparmiEnergetico: "Risparmio Energetico",
    risparmiEnergeticoDesc: "Ottimizzazione consumi e efficienza energetica",
    certificatiAcqua: "Certificati Acqua",
    certificatiAcquaDesc: "Conservazione e uso responsabile delle risorse idriche",
    integrazioneDpp: "Integrazione con Digital Product Passports (DPP)",
    integrazioneDppDesc: "Virtuosity sarà tra le prime piattaforme europee ad integrare i Digital Product Passports, rivoluzionando la tracciabilità e sostenibilità dei prodotti secondo la normativa EU 2024",
    privacySecurity: "Privacy e Sicurezza con Zero-Knowledge Proofs",
    privacyDesc: "La tua privacy è al sicuro grazie alle Zero-Knowledge Proofs (ZKP), che permettono di verificare i tuoi comportamenti sostenibili senza rivelare dati personali sensibili",
    perCittadini: "Per i Cittadini",
    perCittadiniDesc: "Premi concreti per comportamenti sostenibili quotidiani",
    perAziende: "Per le Aziende",
    perAziendeDesc: "Strumenti ESG avanzati e coinvolgimento dei dipendenti",
    perCitta: "Per le Città",
    perCittaDesc: "Dati real-time per politiche di sostenibilità efficaci",
    ilNostroTeam: "Il Nostro Team",
    iNostriAdvisors: "I Nostri Advisors",
    offertaCommerciale: "Offerta Commerciale",
    pianoMicro: "Piano Micro",
    pianoPMI: "Piano PMI",
    pianoEnterprise: "Piano Enterprise",
    iniziaSubito: "Inizia Subito",
    contattaci: "Contattaci",
    // Additional About page translations
    fourCertificateTypes: "I 4 Tipi di Certificati Virtuosity",
    certificateTypesDesc: "Ogni azione sostenibile genera certificati blockchain specifici per categoria ambientale, garantendo tracciabilità e valore misurabile ai tuoi comportamenti virtuosi.",
    whatAreDpp: "Cosa sono i DPP",
    dppPassportsRequired: "Passaporti Digitali Obbligatori:",
    dppPassportsRequiredDesc: "Dal 2026, ogni prodotto venduto in EU avrà un QR code con informazioni complete su origine, materiali, impatto ambientale e riciclabilità",
    dppCompleteTraceability: "Tracciabilità Completa:",
    dppCompleteTraceabilityDesc: "Ogni fase del ciclo di vita del prodotto viene registrata in modo immutabile su blockchain",
    dppTotalTransparency: "Trasparenza Totale:",
    dppTotalTransparencyDesc: "Consumatori e aziende possono verificare istantaneamente l'autenticità e sostenibilità di ogni prodotto",
    howVirtusosityIntegratesDpp: "Come Virtuosity Integra i DPP",
    dppAutomaticScanning: "Scansione Automatica:",
    dppAutomaticScanningDesc: "L'app rileva automaticamente i QR code DPP durante gli acquisti, calcolando l'impatto ambientale in tempo reale",
    dppSustainableChoiceRewards: "Premi per Scelte Sostenibili:",
    dppSustainableChoiceRewardsDesc: "Acquistare prodotti con DPP ad alto rating di sostenibilità genera certificati e ricompense extra",
    dppAdvancedAnalytics: "Analytics Avanzate:",
    dppAdvancedAnalyticsDesc: "Dashboard personalizzate mostrano l'impatto ambientale dei tuoi acquisti e suggeriscono alternative più sostenibili",
    dppWorkflowTitle: "Il Flusso di Lavoro DPP in Virtuosity",
    dppQrScanning: "Scansione QR",
    dppQrScanningDesc: "App rileva automaticamente DPP durante acquisti o uso prodotti",
    dppBlockchainValidation: "Validazione Blockchain",
    dppBlockchainValidationDesc: "Verifica autenticità e calcola impact score basato su dati DPP",
    dppCertificateGeneration: "Generazione Certificati",
    dppCertificateGenerationDesc: "Crea certificati ESG basati su sostenibilità prodotto acquistato",
    dppRewardsInsights: "Premi & Insights",
    dppRewardsInsightsDesc: "Sblocca ricompense e ricevi suggerimenti per scelte più sostenibili",
    dppCompetitiveAdvantages: "Vantaggi Competitivi",
    dppCompetitiveAdvantagesDesc: "Con l'integrazione DPP, Virtuosity diventa l'unica piattaforma che collega automaticamente le scelte di consumo sostenibile con un sistema di incentivi concreti, preparando utenti e aziende alla nuova era della trasparenza ambientale europea.",
    whatAreZkProofs: "Cosa sono le Zero-Knowledge Proofs",
    zkProofWithoutRevelation: "Prova senza Rivelazione:",
    zkProofWithoutRevelationDesc: "Le ZKP permettono di dimostrare che hai compiuto un'azione sostenibile senza rivelare dettagli personali come posizione esatta, orari specifici o abitudini",
    zkAdvancedCryptography: "Crittografia Avanzata:",
    zkAdvancedCryptographyDesc: "Utilizzano algoritmi matematici complessi per creare prove verificabili senza esporre i dati sottostanti",
    zkIndustryStandard: "Standard Industriale:",
    zkIndustryStandardDesc: "Tecnologia utilizzata da blockchain leader come Ethereum e protocolli DeFi per garantire privacy e sicurezza",
    howZkWorksInVirtuosity: "Come Funziona in Virtuosity",
    zkMinimalDataCollection: "Raccolta Dati Minimale:",
    zkMinimalDataCollectionDesc: "L'app rileva solo l'essenziale (es. \"hai usato una bici\") senza registrare percorsi dettagliati o orari precisi",
    zkProofGeneration: "Proof Generation:",
    zkProofGenerationDesc: "I tuoi dispositivi generano localmente prove crittografiche che dimostrano l'azione sostenibile senza inviare dati raw",
    zkBlockchainVerification: "Verifica Blockchain:",
    zkBlockchainVerificationDesc: "Le prove vengono verificate sulla blockchain senza mai esporre i tuoi dati personali, generando certificati anonimi",
    zkExampleTitle: "Esempio Pratico: Come Funziona",
    zkSustainableAction: "Azione Sostenibile",
    zkSustainableActionDesc: "Usi una bici elettrica per 5km",
    zkZkpGeneration: "Generazione ZKP",
    zkZkpGenerationDesc: "Il tuo phone crea una prova: \"ho risparmiato CO2\" senza rivelare dove/quando",
    zkBlockchainVerificationStep: "Verifica Blockchain",
    zkBlockchainVerificationStepDesc: "La rete valida la prova senza accedere ai tuoi dati personali",
    zkAnonymousCertificate: "Certificato Anonimo",
    zkAnonymousCertificateDesc: "Ricevi certificati CO2 verificabili ma completamente anonimi",
    zkTotalAnonymity: "Anonimato Totale",
    zkTotalAnonymityDesc: "Nessun dato personale identificabile viene mai memorizzato o trasmesso. Solo le prove matematiche delle tue azioni sostenibili.",
    zkLocalProcessing: "Elaborazione Locale",
    zkLocalProcessingDesc: "Le ZKP vengono generate direttamente sul tuo dispositivo. I dati sensibili non lasciano mai il tuo telefono.",
    zkGdprCompliance: "Conformità GDPR",
    zkGdprComplianceDesc: "Privacy by design e conformità totale alle normative europee. I tuoi diritti digitali sono sempre protetti.",
    zkPrivacyFirstTitle: "Privacy First, Sostenibilità Sempre",
    zkPrivacyFirstDesc: "Con Virtuosity, la tua privacy non è negoziabile. Le Zero-Knowledge Proofs garantiscono che puoi dimostrare il tuo impegno per l'ambiente mantenendo il controllo totale sui tuoi dati personali.",
    exchangeModelsTitle: "Modelli di Scambio Certificati",
    employeeCompanyExchange: "Dipendente ↔ Azienda",
    employeeCompanyExchangeDesc: "Scambio di certificati sostenibili in cambio di welfare aziendale",
    citizenMunicipalityExchange: "Cittadino ↔ Comune",
    citizenMunicipalityExchangeDesc: "Scambio di certificati sostenibili per servizi e agevolazioni comunali",
    howItWorks: "Come Funziona",
    employeeExchangeDesc: "I dipendenti accumulano certificati attraverso comportamenti sostenibili e li scambiano con l'azienda per ottenere benefit welfare personalizzati, migliorando engagement e ESG score aziendale.",
    citizenExchangeDesc: "I cittadini virtuosi accumulano certificati attraverso comportamenti sostenibili quotidiani e li riscattano presso il comune per ottenere servizi, agevolazioni e accessi prioritari, contribuendo agli obiettivi di sostenibilità urbana.",
    practicalWelfareExamples: "Esempi Pratici di Welfare",
    practicalServicesExamples: "Esempi Pratici di Servizi",
    sustainableMobility: "🚗 Mobilità Sostenibile",
    smartWorkingGreen: "🏠 Smart Working Green",
    trainingDevelopment: "🎯 Formazione & Sviluppo",
    publicTransport: "🚌 Trasporti Pubblici",
    cultureLeisure: "🎭 Cultura & Tempo Libero",
    taxBenefits: "🏛️ Agevolazioni Fiscali",
    certificatesRequired: "Certificati richiesti:",
    benefitObtained: "Benefit ottenuto:",
    serviceObtained: "Servizio ottenuto:",
    sustainableMobilityReq: "50 certificati CO2 (equivalenti a 100km in bici)",
    sustainableMobilityBenefit: "Rimborso parcheggio aziendale per 1 mese o abbonamento car sharing",
    smartWorkingReq: "30 certificati Energia + 20 certificati CO2",
    smartWorkingBenefit: "Giorni di smart working extra o rimborso bollette per home office sostenibile",
    trainingReq: "100 certificati misti (CO2 + Rifiuti + Acqua)",
    trainingBenefit: "Corso di formazione professionale o master in sostenibilità aziendale",
    publicTransportReq: "40 certificati CO2 (equivalenti a 80km in mezzi sostenibili)",
    publicTransportService: "Abbonamento mensile gratuito bus/metro o 20 corse bike sharing",
    cultureReq: "25 certificati Rifiuti + 15 certificati Acqua",
    cultureService: "Ingressi gratuiti a musei comunali, teatro e biblioteche per 1 mese",
    taxBenefitsReq: "80 certificati misti (tutti i tipi)",
    taxBenefitsService: "Riduzione 30% TARI o parcheggi gratuiti in centro per 2 mesi",
    companyAdvantages: "Vantaggi per l'Azienda",
    municipalityAdvantages: "Vantaggi per il Comune",
    ecosystemTitle: "Ecosistema Virtuosity: Win-Win per Tutti",
    ecosystemDesc: "Ogni certificato sostenibile genera valore concreto per cittadini, aziende e istituzioni, creando un circolo virtuoso dove la sostenibilità diventa economicamente vantaggiosa per tutti gli attori coinvolti.",
    stakeholderBenefitsTitle: "Vantaggi per Tutti gli Stakeholder",
    integrationsTitle: "Integrazioni & Possibili Partnership",
    bikeSharing: "Bike Sharing",
    carSharing: "Car Sharing",
    publicTransportProviders: "Trasporti Pubblici",
    fitnessTracking: "Fitness Tracking",
    smartParking: "Smart Parking",
    eScooters: "E-Scooters",
    techStackTitle: "Stack Tecnologico",
    techStackDesc: "Tecnologie all'avanguardia per la sostenibilità del futuro",
    frontend: "Frontend",
    blockchain: "Blockchain",
    backend: "Backend",
    compliance: "Compliance",
    roadmapTitle: "La Nostra Roadmap",
    mvpPilotCities: "MVP & Pilot Cities",
    expansionPartnerships: "Espansione & Partnership",
    marketplaceBlockchain: "Marketplace & Blockchain",
    europeanScaleAi: "Scala Europea & IA",
    businessInfoTitle: "Informazioni Aziendali",
    contactInfo: "Contact Info",
    readyToStartTitle: "Pronto a Iniziare il Tuo Viaggio Sostenibile?",
    readyToStartDesc: "Unisciti a migliaia di cittadini che stanno già facendo la differenza per il pianeta",
    digitalEcosystemTitle: "Un ecosistema digitale per trasformare la sostenibilità in valore",
    digitalEcosystemDesc: "Contattaci per iniziare il tuo viaggio verso la sostenibilità digitale",
    perfectForFreelance: "Perfetto per P.IVA e micro aziende",
    idealForSme: "Ideale per aziende 20-250 dipendenti",
    forLargeCompanies: "Per aziende +250 dipendenti e Comuni",
    monthlyPrice: "/mese",
    everythingFromMicro: "Tutto del piano Micro +",
    everythingFromSme: "Tutto del piano PMI +",
    unlimitedBlockchainCerts: "Certificati blockchain illimitati",
    basicEsgDashboard: "Dashboard ESG basic",
    exchangeAccess: "Accesso Exchange",
    advancedEsgDashboard: "Dashboard ESG avanzata",
    automaticCsrdReports: "Report automatici CSRD/ESRS",
    corporateWelfareSystem: "Sistema welfare aziendale",
    apiIntegration: "API integration",
    whiteLabelSolution: "White label solution",
    completeDppIntegration: "Integrazione DPP completa",
    predictiveAiAnalytics: "Analytics predittive IA",
    dedicatedAccountManager: "Account manager dedicato",
    companyAdvantagesList: [
      "• Miglioramento ESG score e reporting automatico",
      "• Maggiore engagement e retention dei dipendenti", 
      "• Riduzione carbon footprint aziendale misurabile",
      "• Attrazione talenti orientati alla sostenibilità"
    ],
    municipalityAdvantagesList: [
      "• Dati real-time su comportamenti sostenibili cittadini",
      "• Raggiungimento obiettivi climatici EU 2030",
      "• Maggiore coinvolgimento e partecipazione civica",
      "• Riduzione costi gestione rifiuti e trasporti"
    ]
  },
  en: {
    // Index page translations
    heroTitle: "Virtuosity",
    heroSubtitle: "An innovative model that stimulates interaction between municipalities, companies and citizens to build a sustainable future together.",
    heroDescription: "The platform that rewards your sustainable behaviors. Automatic tracking, blockchain certificates and real rewards for a greener future.",
    buttonVirtusosity: "Virtusosity",
    buttonUser: "User",
    buttonExchange: "Exchange",
    buttonCompanies: "Companies",
    buttonMunicipalities: "Municipalities",
    switchToEnglish: "Passa all'Italiano",
    englishVersion: "Versione Italiana",
    englishComingSoon: "Traduzione italiana già disponibile! 🇮🇹",
    reportTitle: "Virtuosity Report",
    reportSubtitle: "Sustainable Activities Report",
    reportDescription: "Complete summary of your activities and certifications - Period: January 2024",
    downloadReport: "Download Report",
    backToDashboard: "Back to Dashboard",
    totalCO2Saved: "Total CO₂ Saved",
    totalPoints: "Total Points",
    certifiedCO2: "Certified CO₂",
    certifiedPoints: "Certified Points",
    activitiesDetail: "Activities Detail",
    activitiesDescription: "Complete list of all registered sustainable activities",
    blockchainCertificates: "Blockchain Certificates",
    certificatesDescription: "Verified and immutable digital certifications",
    backToMenu: "Back to Menu",
    employeeCertificates: "Employee Certificates",
    externalCertificates: "External Certificates",
    employeeCertificatesDesc: "DPP certificates received from company employees",
    externalCertificatesDesc: "DPP certificates received from external subjects",
    welfareTitle: "Corporate Welfare, Rewards and Gadgets",
    welfareDescription: "Manage welfare rewards, corporate gadgets and prize trips available for employees",
    type: "Type",
    name: "Name",
    value: "Value",
    add: "Add",
    sustainabilityReport: "Sustainability Report",
    sustainabilityDescription: "Generate reports with data for corporate sustainability reporting",
    certifyAndCompensate: "Certify and Compensate",
    close: "Close",
    exportReport: "Export Report",
    activityType: "Type",
    activity: "Activity",
    distance: "Distance",
    co2Saved: "CO₂ Saved",
    points: "Points",
    date: "Date",
    location: "Location",
    id: "ID",
    title: "Title",
    certifiedCO2Short: "Certified CO₂",
    validationDate: "Validation Date",
    blockchainHash: "Blockchain Hash",
    status: "Status",
    verified: "Verified",
    aboutValueOfActions: "The value of daily actions",
    aboutOurMission: "Our Mission",
    aboutMissionText: "Democratize sustainability through blockchain technology, making every sustainable action measurable, verifiable and rewarding. We build a future where making the right choice for the planet also becomes the most convenient choice for people.",
    aboutHowItWorks: "How Virtuosity Works",
    aboutStartNow: "Start Now",
    aboutHome: "Home",
    aboutBackHome: "Back to Home",
    // New About page translations
    aboutDescription: "Virtuosity is the first European platform that automatically transforms sustainable behaviors into verifiable certificates, creating an ecosystem of concrete incentives for citizens, companies and public administrations.",
    trackingAutomatico: "Automatic Tracking",
    trackingDesc: "No manual input. Your sustainable actions are automatically detected through phone sensors and integrations with external apps.",
    certificazioneBlockchain: "Blockchain Certification",
    certificazioneDesc: "Every action generates 4 types of verifiable and immutable digital certificates on Ethereum/Polygon blockchain: CO2, Waste and Recycling, Energy Saving and Water.",
    premiReali: "Real Rewards",
    premiDesc: "Convert your certificates into corporate benefits, transport discounts, free admissions and much more through the integrated marketplace.",
    communityGamification: "Community & Gamification",
    communityDesc: "Participate in challenges, earn badges, climb leaderboards and connect with other virtuous citizens in the sustainable community.",
    certificatiCO2: "CO2 Certificates",
    certificatiCO2Desc: "Emission reduction through sustainable mobility",
    rifiutiRiciclo: "Waste and Recycling",
    rifiutiRicicloDesc: "Responsible management and recycling of materials",
    risparmiEnergetico: "Energy Saving",
    risparmiEnergeticoDesc: "Consumption optimization and energy efficiency",
    certificatiAcqua: "Water Certificates",
    certificatiAcquaDesc: "Conservation and responsible use of water resources",
    integrazioneDpp: "Integration with Digital Product Passports (DPP)",
    integrazioneDppDesc: "Virtuosity will be among the first European platforms to integrate Digital Product Passports, revolutionizing product traceability and sustainability according to EU 2024 regulations",
    privacySecurity: "Privacy and Security with Zero-Knowledge Proofs",
    privacyDesc: "Your privacy is safe thanks to Zero-Knowledge Proofs (ZKP), which allow verifying your sustainable behaviors without revealing sensitive personal data",
    perCittadini: "For Citizens",
    perCittadiniDesc: "Concrete rewards for daily sustainable behaviors",
    perAziende: "For Companies",
    perAziendeDesc: "Advanced ESG tools and employee engagement",
    perCitta: "For Cities",
    perCittaDesc: "Real-time data for effective sustainability policies",
    ilNostroTeam: "Our Team",
    iNostriAdvisors: "Our Advisors",
    offertaCommerciale: "Commercial Offer",
    pianoMicro: "Micro Plan",
    pianoPMI: "SME Plan",
    pianoEnterprise: "Enterprise Plan",
    iniziaSubito: "Start Now",
    contattaci: "Contact Us",
    // Additional About page translations
    fourCertificateTypes: "The 4 Types of Virtuosity Certificates",
    certificateTypesDesc: "Every sustainable action generates specific blockchain certificates for environmental categories, ensuring traceability and measurable value for your virtuous behaviors.",
    whatAreDpp: "What are DPPs",
    dppPassportsRequired: "Mandatory Digital Passports:",
    dppPassportsRequiredDesc: "From 2026, every product sold in EU will have a QR code with complete information on origin, materials, environmental impact and recyclability",
    dppCompleteTraceability: "Complete Traceability:",
    dppCompleteTraceabilityDesc: "Every phase of the product lifecycle is recorded immutably on blockchain",
    dppTotalTransparency: "Total Transparency:",
    dppTotalTransparencyDesc: "Consumers and companies can instantly verify the authenticity and sustainability of every product",
    howVirtusosityIntegratesDpp: "How Virtuosity Integrates DPPs",
    dppAutomaticScanning: "Automatic Scanning:",
    dppAutomaticScanningDesc: "The app automatically detects DPP QR codes during purchases, calculating environmental impact in real-time",
    dppSustainableChoiceRewards: "Sustainable Choice Rewards:",
    dppSustainableChoiceRewardsDesc: "Purchasing products with high sustainability rating DPPs generates certificates and extra rewards",
    dppAdvancedAnalytics: "Advanced Analytics:",
    dppAdvancedAnalyticsDesc: "Personalized dashboards show the environmental impact of your purchases and suggest more sustainable alternatives",
    dppWorkflowTitle: "The DPP Workflow in Virtuosity",
    dppQrScanning: "QR Scanning",
    dppQrScanningDesc: "App automatically detects DPP during purchases or product use",
    dppBlockchainValidation: "Blockchain Validation",
    dppBlockchainValidationDesc: "Verifies authenticity and calculates impact score based on DPP data",
    dppCertificateGeneration: "Certificate Generation",
    dppCertificateGenerationDesc: "Creates ESG certificates based on purchased product sustainability",
    dppRewardsInsights: "Rewards & Insights",
    dppRewardsInsightsDesc: "Unlock rewards and receive suggestions for more sustainable choices",
    dppCompetitiveAdvantages: "Competitive Advantages",
    dppCompetitiveAdvantagesDesc: "With DPP integration, Virtuosity becomes the only platform that automatically connects sustainable consumption choices with a concrete incentive system, preparing users and companies for the new era of European environmental transparency.",
    whatAreZkProofs: "What are Zero-Knowledge Proofs",
    zkProofWithoutRevelation: "Proof without Revelation:",
    zkProofWithoutRevelationDesc: "ZKPs allow proving that you performed a sustainable action without revealing personal details like exact location, specific times or habits",
    zkAdvancedCryptography: "Advanced Cryptography:",
    zkAdvancedCryptographyDesc: "Use complex mathematical algorithms to create verifiable proofs without exposing underlying data",
    zkIndustryStandard: "Industry Standard:",
    zkIndustryStandardDesc: "Technology used by leading blockchains like Ethereum and DeFi protocols to ensure privacy and security",
    howZkWorksInVirtuosity: "How it Works in Virtuosity",
    zkMinimalDataCollection: "Minimal Data Collection:",
    zkMinimalDataCollectionDesc: "The app detects only the essential (e.g. \"you used a bike\") without recording detailed routes or precise times",
    zkProofGeneration: "Proof Generation:",
    zkProofGenerationDesc: "Your devices locally generate cryptographic proofs that demonstrate sustainable action without sending raw data",
    zkBlockchainVerification: "Blockchain Verification:",
    zkBlockchainVerificationDesc: "Proofs are verified on blockchain without ever exposing your personal data, generating anonymous certificates",
    zkExampleTitle: "Practical Example: How it Works",
    zkSustainableAction: "Sustainable Action",
    zkSustainableActionDesc: "You use an electric bike for 5km",
    zkZkpGeneration: "ZKP Generation",
    zkZkpGenerationDesc: "Your phone creates a proof: \"I saved CO2\" without revealing where/when",
    zkBlockchainVerificationStep: "Blockchain Verification",
    zkBlockchainVerificationStepDesc: "The network validates the proof without accessing your personal data",
    zkAnonymousCertificate: "Anonymous Certificate",
    zkAnonymousCertificateDesc: "You receive verifiable but completely anonymous CO2 certificates",
    zkTotalAnonymity: "Total Anonymity",
    zkTotalAnonymityDesc: "No identifiable personal data is ever stored or transmitted. Only mathematical proofs of your sustainable actions.",
    zkLocalProcessing: "Local Processing",
    zkLocalProcessingDesc: "ZKPs are generated directly on your device. Sensitive data never leaves your phone.",
    zkGdprCompliance: "GDPR Compliance",
    zkGdprComplianceDesc: "Privacy by design and full compliance with European regulations. Your digital rights are always protected.",
    zkPrivacyFirstTitle: "Privacy First, Sustainability Always",
    zkPrivacyFirstDesc: "With Virtuosity, your privacy is non-negotiable. Zero-Knowledge Proofs ensure you can prove your environmental commitment while maintaining total control over your personal data.",
    exchangeModelsTitle: "Certificate Exchange Models",
    employeeCompanyExchange: "Employee ↔ Company",
    employeeCompanyExchangeDesc: "Exchange of sustainable certificates for corporate welfare",
    citizenMunicipalityExchange: "Citizen ↔ Municipality",
    citizenMunicipalityExchangeDesc: "Exchange of sustainable certificates for municipal services and benefits",
    howItWorks: "How it Works",
    employeeExchangeDesc: "Employees accumulate certificates through sustainable behaviors and exchange them with the company for personalized welfare benefits, improving engagement and corporate ESG score.",
    citizenExchangeDesc: "Virtuous citizens accumulate certificates through daily sustainable behaviors and redeem them with the municipality for services, benefits and priority access, contributing to urban sustainability goals.",
    practicalWelfareExamples: "Practical Welfare Examples",
    practicalServicesExamples: "Practical Service Examples",
    sustainableMobility: "🚗 Sustainable Mobility",
    smartWorkingGreen: "🏠 Green Smart Working",
    trainingDevelopment: "🎯 Training & Development",
    publicTransport: "🚌 Public Transport",
    cultureLeisure: "🎭 Culture & Leisure",
    taxBenefits: "🏛️ Tax Benefits",
    certificatesRequired: "Certificates required:",
    benefitObtained: "Benefit obtained:",
    serviceObtained: "Service obtained:",
    sustainableMobilityReq: "50 CO2 certificates (equivalent to 100km by bike)",
    sustainableMobilityBenefit: "Company parking reimbursement for 1 month or car sharing subscription",
    smartWorkingReq: "30 Energy certificates + 20 CO2 certificates",
    smartWorkingBenefit: "Extra smart working days or sustainable home office bill reimbursement",
    trainingReq: "100 mixed certificates (CO2 + Waste + Water)",
    trainingBenefit: "Professional training course or sustainability master's degree",
    publicTransportReq: "40 CO2 certificates (equivalent to 80km in sustainable transport)",
    publicTransportService: "Free monthly bus/metro subscription or 20 bike sharing rides",
    cultureReq: "25 Waste certificates + 15 Water certificates",
    cultureService: "Free access to municipal museums, theater and libraries for 1 month",
    taxBenefitsReq: "80 mixed certificates (all types)",
    taxBenefitsService: "30% TARI reduction or free city center parking for 2 months",
    companyAdvantages: "Company Advantages",
    municipalityAdvantages: "Municipality Advantages",
    ecosystemTitle: "Virtuosity Ecosystem: Win-Win for Everyone",
    ecosystemDesc: "Every sustainable certificate generates concrete value for citizens, companies and institutions, creating a virtuous circle where sustainability becomes economically advantageous for all involved actors.",
    stakeholderBenefitsTitle: "Benefits for All Stakeholders",
    integrationsTitle: "Integrations & Possible Partnerships",
    bikeSharing: "Bike Sharing",
    carSharing: "Car Sharing",
    publicTransportProviders: "Public Transport",
    fitnessTracking: "Fitness Tracking",
    smartParking: "Smart Parking",
    eScooters: "E-Scooters",
    techStackTitle: "Technology Stack",
    techStackDesc: "Cutting-edge technologies for the sustainability of the future",
    frontend: "Frontend",
    blockchain: "Blockchain",
    backend: "Backend",
    compliance: "Compliance",
    roadmapTitle: "Our Roadmap",
    mvpPilotCities: "MVP & Pilot Cities",
    expansionPartnerships: "Expansion & Partnerships",
    marketplaceBlockchain: "Marketplace & Blockchain",
    europeanScaleAi: "European Scale & AI",
    businessInfoTitle: "Business Information",
    contactInfo: "Contact Info",
    readyToStartTitle: "Ready to Start Your Sustainable Journey?",
    readyToStartDesc: "Join thousands of citizens who are already making a difference for the planet",
    digitalEcosystemTitle: "A digital ecosystem to transform sustainability into value",
    digitalEcosystemDesc: "Contact us to start your journey towards digital sustainability",
    perfectForFreelance: "Perfect for freelancers and micro companies",
    idealForSme: "Ideal for companies with 20-250 employees",
    forLargeCompanies: "For companies with +250 employees and Municipalities",
    monthlyPrice: "/month",
    everythingFromMicro: "Everything from Micro plan +",
    everythingFromSme: "Everything from SME plan +",
    unlimitedBlockchainCerts: "Unlimited blockchain certificates",
    basicEsgDashboard: "Basic ESG dashboard",
    exchangeAccess: "Exchange access",
    advancedEsgDashboard: "Advanced ESG dashboard",
    automaticCsrdReports: "Automatic CSRD/ESRS reports",
    corporateWelfareSystem: "Corporate welfare system",
    apiIntegration: "API integration",
    whiteLabelSolution: "White label solution",
    completeDppIntegration: "Complete DPP integration",
    predictiveAiAnalytics: "Predictive AI analytics",
    dedicatedAccountManager: "Dedicated account manager",
    companyAdvantagesList: [
      "• ESG score improvement and automatic reporting",
      "• Greater employee engagement and retention",
      "• Measurable corporate carbon footprint reduction",
      "• Attraction of sustainability-oriented talent"
    ],
    municipalityAdvantagesList: [
      "• Real-time data on citizen sustainable behaviors",
      "• Achievement of EU 2030 climate goals",
      "• Greater involvement and civic participation",
      "• Reduction of waste management and transport costs"
    ]
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('it');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['it']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
